# Generated by Django 4.2.16 on 2025-06-05 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fungalmaterials", "0006_alter_material_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="article",
            name="year",
            field=models.PositiveIntegerField(
                help_text="Year published online",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1850),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="abstract",
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="review",
            name="year",
            field=models.PositiveIntegerField(
                help_text="Year published online",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1850),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
    ]
